apiVersion: v1
kind: Service
metadata:
  name: mi-load-balancer
  labels:
    service: servidor-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    service: servidor-web
